const C=window.DICE_DUEL_CONFIG||{},db=C.SUPABASE_URL&&C.SUPABASE_ANON_KEY?supabase.createClient(C.SUPABASE_URL,C.SUPABASE_ANON_KEY):null;
let game=null,my=0,channel=null,busy=false;
const $=x=>document.getElementById(x), show=x=>{document.querySelectorAll(".view").forEach(v=>v.classList.add("hidden"));$(x).classList.remove("hidden")};
function toast(x){let t=$("toast");t.textContent=x;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2400)}
function code(){let a="ABCDEFGHJKLMNPQRSTUVWXYZ23456789",s="";for(let i=0;i<6;i++)s+=a[Math.floor(Math.random()*a.length)];return s}
function clean(x){return(x||"").toUpperCase().replace(/[^A-Z0-9]/g,"").slice(0,6)}
function requireDb(){if(!db){toast("Bitte zuerst config.js mit Supabase verbinden.");return false}return true}
$("configHint").textContent=db?"":"⚙️ Supabase ist noch nicht konfiguriert.";
$("create").onclick=async()=>{if(!requireDb())return;let name=$("createName").value.trim()||"Spieler 1",start=Math.floor(Number($("start").value));if(!Number.isSafeInteger(start)||start<2)return toast("Startzahl muss mindestens 2 sein.");for(let i=0;i<8;i++){let c=code(),r=await db.from("games").insert({room_code:c,host_name:name,start_number:start,current_number:start,turn:1,status:"waiting",history:[]}).select().single();if(!r.error){game=r.data;my=1;subscribe();$("lobbyCode").textContent=c;show("lobby");return}}toast("Raum konnte nicht erstellt werden.")};
$("join").onclick=async()=>{if(!requireDb())return;let name=$("joinName").value.trim()||"Spieler 2",c=clean($("code").value);if(c.length!==6)return toast("Bitte 6-stelligen Code eingeben.");let r=await db.from("games").select("*").eq("room_code",c).maybeSingle();if(r.error||!r.data)return toast("Raum nicht gefunden.");if(r.data.status!=="waiting"||r.data.guest_name)return toast("Raum ist bereits voll.");let u=await db.from("games").update({guest_name:name,status:"playing",updated_at:new Date().toISOString()}).eq("id",r.data.id).select().single();if(u.error)return toast("Beitritt fehlgeschlagen.");game=u.data;my=2;subscribe();render()};
$("code").oninput=e=>e.target.value=clean(e.target.value);
$("copyCode").onclick=()=>navigator.clipboard.writeText(game.room_code).then(()=>toast("Code kopiert!"));
$("copyLink").onclick=()=>navigator.clipboard.writeText(location.origin+location.pathname+"?room="+game.room_code).then(()=>toast("Einladungslink kopiert!"));
$("leave").onclick=()=>{if(confirm("Spiel verlassen?")){if(channel)db.removeChannel(channel);game=null;show("home")}};
$("homeBtn").onclick=()=>{if(channel)db.removeChannel(channel);game=null;show("home")};
function subscribe(){if(channel)db.removeChannel(channel);channel=db.channel("game-"+game.id).on("postgres_changes",{event:"UPDATE",schema:"public",table:"games",filter:"id=eq."+game.id},p=>{game=p.new;render();if(game.status==="finished")setTimeout(result,500)}).subscribe()}
function render(){if(game.status==="waiting"){$("lobbyCode").textContent=game.room_code;$("wait").textContent=game.guest_name?"Spieler 2 ist da!":"⏳ Warte auf Spieler 2…";show("lobby");return}$("gameCode").textContent=game.room_code;$("p1name").textContent=game.host_name;$("p2name").textContent=game.guest_name||"Wartet…";$("number").textContent=game.current_number;$("p1").classList.toggle("active",game.turn===1&&game.status==="playing");$("p2").classList.toggle("active",game.turn===2&&game.status==="playing");$("p1turn").textContent=game.turn===1?"AM ZUG":"READY";$("p2turn").textContent=game.turn===2?"AM ZUG":"READY";$("turnText").textContent=game.status==="playing"?(game.turn===my?"DU BIST DRAN":(game.turn===1?game.host_name:game.guest_name)+" IST DRAN"):"";$("roll").disabled=game.status!=="playing"||game.turn!==my||busy;let h=$("history");h.innerHTML="";(game.history||[]).slice().reverse().forEach(x=>{let d=document.createElement("div");d.innerHTML="<strong>Spieler "+x.player+"</strong> · "+x.from+" → <b>"+x.roll+"</b>";h.appendChild(d)});if(!(game.history||[]).length)h.innerHTML='<div style="color:#8d94a8">Noch keine Würfe.</div>';show("game")}
$("roll").onclick=async()=>{if(!game||busy||game.turn!==my||game.status!=="playing")return;busy=true;$("roll").classList.add("rolling");await new Promise(r=>setTimeout(r,550));let old=game.current_number,roll=Math.floor(Math.random()*old)+1,h=[...(game.history||[]),{player:my,from:old,roll}],u={current_number:roll,history:h,updated_at:new Date().toISOString()};if(roll===1){u.status="finished";u.loser=my;u.winner=my===1?2:1}else u.turn=my===1?2:1;let r=await db.from("games").update(u).eq("id",game.id).eq("turn",my).eq("status","playing").select().single();busy=false;$("roll").classList.remove("rolling");if(r.error||!r.data)return toast("Wurf konnte nicht gespeichert werden.");game=r.data;$("rollResult").textContent=roll===1?"💀 1":roll;$("rollResult").animate([{transform:"scale(.5)",opacity:0},{transform:"scale(1.15)",opacity:1},{transform:"scale(1)",opacity:1}],{duration:450});render();if(game.status==="finished")setTimeout(result,550)};
function result(){if(!game||game.status!=="finished")return;let won=game.winner===my;$("emoji").textContent=won?"🏆":"💀";$("resultTitle").textContent=won?"DU GEWINNST!":"DU VERLIERST!";let loser=game.loser===1?game.host_name:game.guest_name,winner=game.winner===1?game.host_name:game.guest_name;$("resultText").textContent=loser+" hat die 1 gewürfelt. "+winner+" gewinnt!";$("resultCard").className="card center result "+(won?"win":"lose");show("result")}
$("rematch").onclick=async()=>{if(my!==1)return toast("Nur Spieler 1 kann das Rematch starten.");let r=await db.from("games").update({current_number:game.start_number,turn:1,status:"playing",winner:null,loser:null,history:[],updated_at:new Date().toISOString()}).eq("id",game.id).select().single();if(r.error)return toast("Rematch fehlgeschlagen.");game=r.data;render()};
let q=new URLSearchParams(location.search).get("room");if(q){$("code").value=clean(q);$("joinName").focus()}
